"""add_vector_embedding_id_to_users

Revision ID: 77e1907f4eb9
Revises: 4425e83ec13c
Create Date: 2025-04-13 05:44:09.950479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e1907f4eb9'
down_revision: Union[str, None] = '4425e83ec13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vector_embedding_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vector_embedding_id')
    # ### end Alembic commands ###
